### ISSUE TITLE
Attention: Please do something to prevent password leaked

### ISSUE THREAD

**Issue by lsvih** [matben/registar_resursa1#1]
hello passer-by. I read a article about cipher leaks today, and tried searching some keyword at github. Then I found this repo, please do something as soon to protect your database and account.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/5164225/33550490-20b7a83e-d929-11e7-8ae8-efe42f2e8b1a.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/5164225/33550500-28022de4-d929-11e7-9df4-ff095c72c280.png">

**Comment by matben** [comment]
thanks a lot.

big mistake.. in hurry i filled wrong .env file.
best regards

**Comment by matben** [comment]
thanks a lot.

big mistake.. in hurry i filled wrong .env file.
best regards

2017-12-04 12:28 GMT+01:00 lsvih <notifications@github.com>:
